### ISSUE TITLE
Automate `cargo-generate` updates

### ISSUE THREAD

**Issue by BD103** [TheBevyFlock/bevy_quickstart#251] opened 2024-08-09 23:03 UTC
See https://discord.com/channels/691052431525675048/1258521739395203174/1271602001502928937 for more context.

**Comment by benfrankel** [comment] 2024-08-09 23:08
Duplicate of https://github.com/TheBevyFlock/bevy_quickstart/issues/129

**Closed** 2024-08-09 23:11 UTC

**Comment by BD103** [comment] 2024-08-09 23:30
Whoops, my bad!
